language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.6
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  python manage.py test application
after_success:
  coveralls
